LOGICAL_OPERATOR_CODE_GEN(kMore       , JUMP_IF_ABOVE, )
LOGICAL_OPERATOR_CODE_GEN(kEqual      , JUMP_IF_EQUAL, )
LOGICAL_OPERATOR_CODE_GEN(kLess       , JUMP_IF_LESS, )
LOGICAL_OPERATOR_CODE_GEN(kLessOrEqual, JUMP_IF_LESS_OR_EQUAL, )
LOGICAL_OPERATOR_CODE_GEN(kMoreOrEqual, JUMP_IF_ABOVE_OR_EQUAL, )
LOGICAL_OPERATOR_CODE_GEN(kNotEqual   , JUMP_IF_NOT_EQUAL, )

LOGICAL_OPERATOR_CODE_GEN(kAnd        , JUMP_IF_ABOVE,
    AND(kRAX, kRBX);
    )

LOGICAL_OPERATOR_CODE_GEN(kOr         , JUMP_IF_ABOVE,
    OR(kRAX, kRBX);
    )
