LOGICAL_OPERATOR_CODE_GEN(kMore       , JUMP_IF_ABOVE,
    CMP_REGISTER_TO_REGISTER(kRAX, kR11);)

LOGICAL_OPERATOR_CODE_GEN(kEqual      , JUMP_IF_EQUAL,
    CMP_REGISTER_TO_REGISTER(kRAX, kR11);)

LOGICAL_OPERATOR_CODE_GEN(kLess       , JUMP_IF_LESS,
    CMP_REGISTER_TO_IMMEDIATE(kRAX, kR11);)

LOGICAL_OPERATOR_CODE_GEN(kLessOrEqual, JUMP_IF_LESS_OR_EQUAL,
    CMP_REGISTER_TO_REGISTER(kRAX, kR11);)

LOGICAL_OPERATOR_CODE_GEN(kMoreOrEqual, JUMP_IF_ABOVE_OR_EQUAL,
    CMP_REGISTER_TO_REGISTER(kRAX, kR11);)

LOGICAL_OPERATOR_CODE_GEN(kNotEqual   , JUMP_IF_NOT_EQUAL,
    CMP_REGISTER_TO_REGISTER(kRAX, kR11);)

LOGICAL_OPERATOR_CODE_GEN(kAnd        , JUMP_IF_ABOVE,
    AND(kRAX, kR11);
    CMP_REGISTER_TO_IMMEDIATE(kRAX, 0);)

LOGICAL_OPERATOR_CODE_GEN(kOr         , JUMP_IF_ABOVE,
    OR(kRAX, kR11);
    CMP_REGISTER_TO_IMMEDIATE(kRAX, 0);)
