DEF_KEYWORD("лежать+сосать"      , "+"             ,kAdd)
DEF_KEYWORD("потерял_птсы"       , "-"             ,kSub)
DEF_KEYWORD("посадить_на_zxc"    , "*"             ,kMult)
DEF_KEYWORD("сплитим_на"         , "/"             ,kDiv)
DEF_KEYWORD("углы_вымеряет"      , "sin"           ,kSin)
DEF_KEYWORD("это_все_преломления", "cos"           ,kCos)
DEF_KEYWORD("соси_бля"           , "floor"         ,kFloor)
DEF_KEYWORD("реквием"            , "diff"          ,kDiff)
DEF_KEYWORD("трент_ультует"      , "sqrt"          ,kSqrt)
DEF_KEYWORD("???"                , "if"            ,kIf)
DEF_KEYWORD("пока"               , "while"         ,kWhile)
DEF_KEYWORD("ты"                 , "="             ,kAssign)
DEF_KEYWORD("больше"             , "more"          ,kMore)
DEF_KEYWORD("меньше"             , "less"          ,kLess)
DEF_KEYWORD("и"                  , "and"           ,kAnd)
DEF_KEYWORD("или"                , "or"            ,kOr)
DEF_KEYWORD("не_меньше"          , "more or equal" ,kMoreOrEqual)
DEF_KEYWORD("не_больше"          , "less or equal" ,kLessOrEqual)
DEF_KEYWORD("точно"              , "equal"         ,kEqual)
DEF_KEYWORD("ты_не"              , "not equal"     ,kNotEqual)
DEF_KEYWORD("стой_блять!"        , "break"         ,kBreak)
DEF_KEYWORD("иди_блять!"         , "continue"      ,kContinue)
DEF_KEYWORD("верни_курьера_блять", "return"        ,kReturn)
DEF_KEYWORD("мать"               , "("             ,kLeftBracket)
DEF_KEYWORD("ебал"               , ")"             ,kRightBracket)
DEF_KEYWORD("стань"              , "{"             ,kLeftZoneBracket)
DEF_KEYWORD("мид"                , "}"             ,kRightZoneBracket)
DEF_KEYWORD(","                  , ","             ,kEnumOp)
DEF_KEYWORD("?"                  , ";"             ,kEndOfLine)
DEF_KEYWORD("долбоеб"            , "int64_t"       ,kDoubleType)
DEF_KEYWORD("пишу_твоей_матери"  , "print"         ,kPrint)
DEF_KEYWORD("скажи_мне"          , "scan"          ,kScan)
DEF_KEYWORD("иди_нахуй"          , "abort"         ,kAbort)
